<a href="https://colab.research.google.com/github/HenHimA1/A1/blob/master/MeanFilter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
import numpy as np

In [108]:
a = [[7, 10, 2, 13, 10, 11, 5, 8, 15],
     [14, 6, 1, 11, 6, 9, 13, 6, 14],
     [2, 1, 5, 11, 1, 15, 15, 6, 5],
     [7, 11, 15, 9, 4, 8, 7, 15, 14],
     [11, 1, 13, 14, 9, 5, 8, 12, 9],
     [5, 6, 1, 3, 3, 7, 5, 12, 9],
     [10, 7, 5, 14, 8, 4, 6, 15, 3],
     [2, 6, 5, 4, 11, 12, 6, 14, 10],
     [11, 5, 7, 1, 6, 1, 14, 15, 9]]

In [109]:
A = np.array(a)
A.shape

(9, 9)

In [110]:
f_mean = np.ones(9)
f_mean

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [111]:
f_mean1 = np.reshape(f_mean, (3,3))
f_mean1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [112]:
kolomA = A.shape[1]
barisA = A.shape[0]
kolomM = f_mean1.shape[1]
barisM = f_mean1.shape[0]

In [113]:
Out = []
for i in range(0, barisA - barisM + 1):
  kolomO = []
  for j in range(0, kolomA - kolomM + 1):
    kolomO.append(np.sum(A[i:i+3,j:j+3]))
  Out.append(kolomO)

In [114]:
A[2:5,2:5]

array([[ 5, 11,  1],
       [15,  9,  4],
       [13, 14,  9]])

In [115]:
O = np.reshape(Out, (7,7))
print(O)

[[48 60 60 87 85 88 87]
 [62 70 63 74 78 94 95]
 [66 80 81 76 72 91 91]
 [70 73 71 62 56 79 91]
 [59 64 70 67 55 74 79]
 [47 51 54 66 62 81 80]
 [58 54 61 61 68 87 92]]
